src/Entity/Employee.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\EmployeeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
class Employee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Type = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?int $rating = null;
    #[ORM\Column(length: 255)]
    private ?string $Disponibilite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function getRating():?int
    {
        return $this->rating;
    }
    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }
    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDisponibilite(): ?string
    {
        return $this->Disponibilite ? 'disponible' : 'indisponible';
    }

    public function setDisponibilite(string $Disponibilite): self
    {
        $this->Disponibilite = $Disponibilite;

        return $this;
    }
}

src/Entity/SuiviReclamation.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * SuiviReclamation
 *
 * @ORM\Table(name="suivi_reclamation", indexes={@ORM\Index(name="CLE_ETRANGERE", columns={"id_reclamation"})})
 * @ORM\Entity
 */
class SuiviReclamation
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string|null
     *
     * @ORM\Column(name="etat_reclamation", type="string", length=255, nullable=true)
     */
    
    private $reponseReclamation;

    /**
     * @var \Reclamation
     *
     * @ORM\ManyToOne(targetEntity="Reclamation")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="id_reclamation", referencedColumnName="Id")
     * })
     */
    private $idReclamation;
    public function getId(): ?int
    {
        return $this->id;
    }

    

    public function getReponseReclamation(): ?string
    {
        return $this->reponseReclamation;
    }

    public function setReponseReclamation(?string $reponseReclamation): self
    {
        $this->reponseReclamation = $reponseReclamation;

        return $this;
    }

    public function getIdReclamation(): ?Reclamation
    {
        return $this->idReclamation;
    }

    public function setIdReclamation(?Reclamation $idReclamation): self
    {
        $this->idReclamation = $idReclamation;

        return $this;
    }


}

src/Form/SuiviReclamationType.php
<?php

namespace App\Form;
use App\Entity\Reclamation;

use App\Entity\SuiviReclamation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Choice;

class SuiviReclamationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            
            ->add('reponseReclamation', TextType::class, [
                'label' => 'Description',
                'required' => true,
                'attr' => [
                    'placeholder' => 'Enter the description here',
                    'class' => 'form-control',
                    
                ],
                'data' => 'Not treated yet','label_attr' => [
                    'style' => 'margin-top: 30px;margin-buttom: 160px; margin-right:40px;'
                ], // set default value
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please enter the description',
                    ]),
                ],
            ])
            ->add('idReclamation', TextType::class, [
                'label' => 'Reclamation',
                'disabled' => true,
                'data' => isset($options['data']) && $options['data']->getIdReclamation() ? $options['data']->getIdReclamation()->getId().' - '.$options['data']->getIdReclamation()->getContenu() : null,
                'label_attr' => [
                    'style' => 'margin-top: 130px; margin-right:30px; position:relative ; bottom:90px;'
                ],
                'constraints' => [
                    new NotBlank([
                        'message' => 'Please select a reclamation',
                    ]),
                ],
            ])
            
           
            ->add('save', SubmitType::class, [
                'label' => 'Create',
                'attr' => [
                    'class' => 'btn btn-primary',
                ],
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => SuiviReclamation::class,
        ]);
    }
}

src/Controller/SuiviReclamationController.php
<?php

namespace App\Controller;
use App\Entity\Reclamation;
use App\Repository\SuiviReclamationRepository;
use App\Entity\SuiviReclamation;
use App\Form\SuiviReclamationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/suivi/reclamation')]
class SuiviReclamationController extends AbstractController
{
    #[Route('/', name: 'app_suivi_reclamation_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $suiviReclamations = $entityManager
            ->getRepository(SuiviReclamation::class)
            ->findAll();

        return $this->render('suivi_reclamation/index.html.twig', [
            'suivi_reclamations' => $suiviReclamations,
        ]);
    }
    #[Route('/frontsuivi', name: 'app_suivi_reclamation_index_front', methods: ['GET'])]
    public function indexfront(EntityManagerInterface $entityManager): Response
    {
        $suiviReclamations = $entityManager
            ->getRepository(SuiviReclamation::class)
            ->findAll();

        return $this->render('suivi_reclamation/indexfrontsuiv.html.twig', [
            'suivi_reclamations' => $suiviReclamations,
        ]);
    }
   # src/Controller/ReclamationController.php




#[Route('/suivistat', name: 'app_suivireclamation_stat', methods: ['GET'])]
public function statistics(SuiviReclamationRepository $repo): Response
{
    $suivi = $repo->countAll();

    dump($suivi); // Dump the value of $suivi to check if it contains the expected value

    return $this->render('reclamation/stats.html.twig', [
        'suivi' => $suivi,
    ]);
}

    
    #[Route('/new', name: 'app_suivi_reclamation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $suiviReclamation = new SuiviReclamation();
        $form = $this->createForm(SuiviReclamationType::class, $suiviReclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($suiviReclamation);
            $entityManager->flush();

            return $this->redirectToRoute('app_suivi_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('suivi_reclamation/new.html.twig', [
            'suivi_reclamation' => $suiviReclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_suivi_reclamation_show', methods: ['GET'])]
    public function show(SuiviReclamation $suiviReclamation): Response
    {
        return $this->render('suivi_reclamation/show.html.twig', [
            'suivi_reclamation' => $suiviReclamation,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_suivi_reclamation_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, SuiviReclamation $suiviReclamation, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SuiviReclamationType::class, $suiviReclamation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_suivi_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('suivi_reclamation/edit.html.twig', [
            'suivi_reclamation' => $suiviReclamation,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_suivi_reclamation_delete', methods: ['POST'])]
    public function delete(Request $request, SuiviReclamation $suiviReclamation, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$suiviReclamation->getId(), $request->request->get('_token'))) {
            $entityManager->remove($suiviReclamation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_suivi_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
    #[Route('/new/{id}', name: 'app_suivi_reclamation_new_answer')]
    public function newAnswer(Request $request, EntityManagerInterface $entityManager, int $id): Response
    {
        $reclamation = $entityManager->getRepository(Reclamation::class)->find($id);
        $reclamation->setEtat(1);
        $entityManager->persist($reclamation);
            $entityManager->flush();
    
        if (!$reclamation) {
            throw $this->createNotFoundException('Reclamation not found');
        }
    
        $suiviReclamation = new SuiviReclamation();
        $suiviReclamation->setIdReclamation($reclamation);
    
        $form = $this->createForm(SuiviReclamationType::class, $suiviReclamation);
        $form->handleRequest($request);
    
        if ($form->isSubmitted()) {
            $entityManager->persist($suiviReclamation);
            $entityManager->flush();
            $reclamation->setEtat(2);
        $entityManager->persist($reclamation);
            $entityManager->flush();
    
            return $this->redirectToRoute('app_suivi_reclamation_index');
        }
    
        return $this->renderForm('suivi_reclamation/new.html.twig', [
            'form' => $form,
        ]);
    }
    #[Route('/suivi-reclamation/chat', name: 'app_suivi_reclamation_chat', methods: ['GET', 'POST'])]
    public function showChat(SuiviReclamationRepository $repository): Response
    {
        $suiviReclamations = $repository->findAll();
    
        return $this->render('suivi_reclamation/chat.html.twig', [
            'suiviReclamations' => $suiviReclamations,
        ]);
    }
    
    

}    

templates/suivi_reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_suivi_reclamation_delete', {'id': suivi_reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ suivi_reclamation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/suivi_reclamation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/suivi_reclamation/chat.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('css/chat.css') }}">
{% endblock %}

{% block chat %}
<section style="background-color: #eee;">
  <div class="container py-5">

    <div class="row d-flex justify-content-center">
      <div class="col-md-8 col-lg-6 col-xl-4">

        <div class="card" id="chat1" style="border-radius: 15px;">
          <div class="card-header d-flex justify-content-between align-items-center p-3 bg-info text-white border-bottom-0"
            style="border-top-left-radius: 15px; border-top-right-radius: 15px;">
            <i class="fas fa-angle-left"></i>
            <p class="mb-0 fw-bold">Live chat</p>
            <i class="fas fa-times"></i>
          </div>
          <div class="card-body">

            <div class="chat-container">
                {% for suiviReclamation in suiviReclamations %}
                <div class="chat-message">
                    <div class="chat-message-header">
                        <strong>{{ suiviReclamation.idReclamation.contenu }}</strong>
                        <span class="chat-message-time">{{ suiviReclamation.idReclamation.datecreation|date('H:i') }}</span>
                    </div>
                    <div class="chat-message-body">
                        <p><strong>Client:</strong> {{ suiviReclamation.reponseReclamation}}</p>
                        {% if suiviReclamation.reponseReclamation is not null %}
                            <p><strong>Agent:</strong> {{ suiviReclamation.reponseReclamation }}</p>
                        {% endif %}
                    </div>
                </div>
                <hr class="my-3">
                {% endfor %}
            </div>

            <div class="form-outline">
              <textarea class="form-control" id="textAreaExample" rows="4"></textarea>
              <label class="form-label" for="textAreaExample">Type your message</label>
              <div class="form-notch">
                <div class="form-notch-leading" style="border-radius: .65rem 0 0 .65rem;"></div>
                <div class="form-notch-middle"></div>
                <div class="form-notch-trailing" style="border-radius: 0 .65rem .65rem 0;"></div>
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>

  </div>
</section>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/chat.js') }}"></script>
{% endblock %}

templates/suivi_reclamation/edit.html.twig
{% extends 'back.html.twig' %}

{% block title %}Edit SuiviReclamation{% endblock %}

{% block body %}
    <div id="page-content">
        <!--Page Title-->
        <div class="page section-header text-center">
            <div class="page-title">
                <div class="wrapper"><h1 class="page-width">Edit SuiviReclamation</h1></div>
            </div>
        </div>
        <!--End Page Title-->

        <div class="card">
            <div class="card-body">
                <div class="form-container">
                    {{ include('suivi_reclamation/_form.html.twig', {'button_label': 'Update'}) }}
                </div>

                <div class="text-center">
                    <a href="{{ path('app_suivi_reclamation_index') }}">Back to list</a>
                </div>

              
            </div>
        </div>
    </div>
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('path/to/style.css') }}">
{% endblock %}

templates/suivi_reclamation/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}SuiviReclamation index{% endblock %}

{% block suivieback %}
    <h1>SuiviReclamation</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>

                

                <th>ReponseReclamation</th>

                <th>Contenu Reclamation</th>

                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for suivi_reclamation in suivi_reclamations %}
            <tr>
                <td>{{ suivi_reclamation.id }}</td>
                
                <td>{{ suivi_reclamation.reponseReclamation }}</td>
                <td>{{ suivi_reclamation.idReclamation.contenu }}</td>

                <td>
                    <a href="{{ path('app_suivi_reclamation_show', {'id': suivi_reclamation.id}) }}"><img src="{{ asset('front/assets/images/detail.png') }}" height="35" width="35"></a>
                    <a href="{{ path('app_suivi_reclamation_edit', {'id': suivi_reclamation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_suivi_reclamation_new') }}">Answer more </a>
{% endblock %}

templates/suivi_reclamation/indexfrontsuiv.html.twig
{% extends 'base.html.twig' %}

{% block title %}SuiviReclamation index{% endblock %}

{% block suivie %}
    <div id="page-content">
        <!--Page Title-->
        <div class="page section-header text-center">
            <div class="page-title">
                <div class="wrapper"><h1 class="page-width">Liste des suivis des réclamations</h1></div>
            </div>
        </div>
        <!--End Page Title-->

        <table class="table">
            <thead>
                <tr>
                    <th>user</th>
                    <th>Réponse de la réclamation</th>
                    <th>Contenu de la réclamation</th>
                </tr>
            </thead>
            <tbody>
                {% for suivi_reclamation in suivi_reclamations %}
                <tr>
                    <td>{{ suivi_reclamation.idReclamation.nom }}</td>
                    <td>{{ suivi_reclamation.reponseReclamation }}</td>
                    <td>{{ suivi_reclamation.idReclamation.contenu }}</td>
                </tr>
                {% else %}
                <tr>
                    <td colspan="5">Aucun enregistrement trouvé</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="text-center">
            <a href="{{ path('app_reclamation_new') }}"></a>
        </div>
    </div>
{% endblock %}

templates/suivi_reclamation/new.html.twig
{% extends 'back.html.twig' %}

{% block title %}Add Suivi Reclamation{% endblock %}

{% block body %}
  <div class="container-fluid py-5">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="card shadow-sm">
          <div class="card-body">
            <h3 class="text-center mb-4">Add Suivi Reclamation</h3>
            <form method="post">
             
              <div class="form-group">
                {{ form_label(form.reponseReclamation, 'Description') }}
                {{ form_widget(form.reponseReclamation, {'attr': {'class': 'form-control', 'rows': 5}}) }}
              </div>
              <div class="form-group">
                {{ form_label(form.idReclamation, 'Réponse') }}
                {{ form_widget(form.idReclamation, {'attr': {'class': 'form-control', 'rows': 3}}) }}
              </div>
              <div class="form-group">
                {{ form_label(form.save, 'Réclamation associée') }}
                {{ form_widget(form.save, {'attr': {'class': 'form-control'}}) }}
              </div>
              <div class="d-flex justify-content-center mt-4">
                <button type="submit" class="btn btn-primary mr-3">Save</button>
                <a href="{{ path('app_suivi_reclamation_index') }}" class="btn btn-secondary">Back to List</a>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/suivi_reclamation/show.html.twig
{% extends 'back.html.twig' %}

{% block title %}SuiviReclamation{% endblock %}

{% block body %}
    <h1>SuiviReclamation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ suivi_reclamation.id }}</td>
            </tr>
            
            <tr>
                <th>ReponseReclamation</th>
                <td>{{ suivi_reclamation.reponseReclamation }}</td>
            </tr>
             <tr>
                <th>contenuReclamation</th>
                <td>{{ suivi_reclamation.idReclamation.contenu }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_suivi_reclamation_index') }}">back to list</a>

    <a href="{{ path('app_suivi_reclamation_edit', {'id': suivi_reclamation.id}) }}">edit</a>

    {{ include('suivi_reclamation/_delete_form.html.twig') }}
{% endblock %}