src/Entity/Employee.php
<?php

namespace App\Entity;
use Symfony\Component\Validator\Constraints as Assert;
use App\Repository\EmployeeRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeeRepository::class)]
class Employee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Nom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Prenom = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Type = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Email = null;

    #[ORM\Column(length: 255)]
    private ?int $rating = null;
    #[ORM\Column(length: 255)]
    private ?string $Disponibilite = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function getRating():?int
    {
        return $this->rating;
    }
    public function setRating(int $rating): self
    {
        $this->rating = $rating;

        return $this;
    }
    public function setPrenom(string $Prenom): self
    {
        $this->Prenom = $Prenom;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->Type;
    }

    public function setType(string $Type): self
    {
        $this->Type = $Type;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->Email;
    }

    public function setEmail(string $Email): self
    {
        $this->Email = $Email;

        return $this;
    }

    public function getDisponibilite(): ?string
    {
        return $this->Disponibilite ? 'disponible' : 'indisponible';
    }

    public function setDisponibilite(string $Disponibilite): self
    {
        $this->Disponibilite = $Disponibilite;

        return $this;
    }
}

src/Entity/Reparation.php
<?php

namespace App\Entity;

use App\Repository\ReparationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection ;
use Symfony\Component\Validator\Constraints as Assert;



#[ORM\Entity(repositoryClass: ReparationRepository::class)]
class Reparation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank(message: "Veuillez remplir ce champ")]
    private ?string $Description_Panne = null;
    #[ORM\OneToMany(mappedBy: 'id_employe', targetEntity: Employee::class,)]
    private Collection $employees;

    #[ORM\Column(length: 255)]
    private ?string $Etat = null;


    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_declaration;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_rep = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $Date_recuperation = null;

    #[ORM\OneToMany(mappedBy: 'reparation', targetEntity: Vehicule::class)]
    private Collection $vehicule;

    #[ORM\Column(type: 'integer')]
    private ?int $id_veh = null;

    public function getIdVeh(): ?int
    {
        return $this->id_veh;
    }

    public function setIdVeh(?int $id_veh): self
    {
        $this->id_veh = $id_veh;

        return $this;
    }

    public function __construct()
    {
        $this->vehicule = new ArrayCollection();
    }





    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescriptionPanne(): ?string
    {
        return $this->Description_Panne;
    }

    public function setDescriptionPanne(?string $Description_Panne): self
    {
        $this->Description_Panne = $Description_Panne;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->Etat ? 'reparé' : 'non reparé';
    }

    public function setEtat(?string $Etat): self
    {
        $this->Etat = $Etat;

        return $this;
    }

    public function getDateRep(): ?\DateTimeInterface
    {
        return $this->Date_rep;
    }

    public function setDateRep(?\DateTimeInterface $Date_rep): self
    {
        $this->Date_rep = $Date_rep;

        return $this;
    }

    public function getDateDeclaration(): ?\DateTimeInterface
    {
        return $this->Date_declaration;
    }

    public function setDateDeclaration(?\DateTimeInterface $Date_declaration): self
    {
        $this->Date_declaration = $Date_declaration;

        return $this;
    }

    public function getDateRecuperation(): ?\DateTimeInterface
    {
        return $this->Date_recuperation;
    }

    public function setDateRecuperation(?\DateTimeInterface $Date_recuperation): self
    {
        $this->Date_recuperation = $Date_recuperation;


        return $this;
    }

    /**
     * @return Collection
     */
    public function getEmployees(): Collection
    {
        return $this->employees;
    }

    /**
     * @param Collection $employees
     */
    public function setEmployees(Collection $employees): void
    {
        $this->employees = $employees;
    }

    /**
     * @return Collection<int, Vehicule>
     */
    public function getVehicule(): Collection
    {
        return $this->vehicule;
    }

    public function addVehicule(Vehicule $vehicule): self
    {
        if (!$this->vehicule->contains($vehicule)) {
            $this->vehicule->add($vehicule);
            $vehicule->setReparation($this);
        }

        return $this;
    }

    public function removeVehicule(Vehicule $vehicule): self
    {
        if ($this->vehicule->removeElement($vehicule)) {
            // set the owning side to null (unless already changed)
            if ($vehicule->getReparation() === $this) {
                $vehicule->setReparation(null);
            }
        }

        return $this;
    }






}

src/Controller/ReclamationController.php
<?php

namespace App\Controller;
use Symfony\Component\HttpFoundation\BinaryFileResponse;
use Symfony\Component\HttpFoundation\ResponseHeaderBag;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use App\Repository\SuiviReclamationRepository;
use App\Repository\RatingRepository;
use App\Repository\VehiculeRepository;
use App\Entity\Rating;
use App\Entity\Vehicule;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use App\Repository\ReclamationRepository;
use App\Entity\Reclamation;
use App\Entity\SuiviReclamation;
use App\Form\ReclamationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormError;
use Symfony\Component\Form\Extension\Core\Type\SearchType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Consoletvs\Profanity\ProfanityFilter;

#[Route('/reclamation')]
class ReclamationController extends AbstractController
{ 
    #[Route('/', name: 'app_reclamation_index', methods: ['GET'])]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $reclamations = $entityManager
            ->getRepository(Reclamation::class)
            ->findAll();

        return $this->render('reclamation/index.html.twig', [
            'reclamations' => $reclamations,
        ]);
    }
    #[Route('/tri', name: 'app_reclamation_index_tri', methods: ['GET'])]
public function tri(EntityManagerInterface $entityManager): Response
{
    $reclamations = $entityManager
        ->getRepository(Reclamation::class)
        ->createQueryBuilder('r')
        ->where('r.datecreation >= :date')
        ->setParameter('date', new \DateTime('-7 days'))
        ->getQuery()
        ->getResult();

    return $this->render('reclamation/indextri.html.twig', [
        'reclamations' => $reclamations,
    ]);
}
#[Route('/triinverse', name: 'app_reclamation_index_tri_inv', methods: ['GET'])]
public function triInv(EntityManagerInterface $entityManager): Response
{
    $reclamations = $entityManager
        ->getRepository(Reclamation::class)
        ->createQueryBuilder('r')
        ->where('r.datecreation < :date')
        ->setParameter('date', new \DateTime('-7 days'))
        ->getQuery()
        ->getResult();

    return $this->render('reclamation/indextri2.html.twig', [
        'reclamations' => $reclamations,
    ]);
}

    #[Route('/test', name: 'app_reclamation_rechercher')]
    public function search(Request $request, ReclamationRepository $reclamationRepository, SerializerInterface $serializer)
    {
        $query = $request->get('query');
        $reclamations = $reclamationRepository->createQueryBuilder('r')
        ->where('r.nom LIKE :query')
        ->setParameter('query',$query . '%')
        ->getQuery()
        ->getResult();
        $json = $serializer->serialize($reclamations, 'json');
        return new JsonResponse($json);
    }

/*
    #[Route('/chart', name: 'app_reclamation_chart', methods: ['GET'])]
    public function chart(ReclamationRepository $repo): Response
    {
        // Get the daily counts from the repository
        $dailyCounts = $repo->countByDay();
    
        return $this->render('reclamation/stats.html.twig', [
            'dailyCounts' => $dailyCounts,
        ]);
    }
    */
    #[Route('/stat', name: 'app_reclamation_stat', methods: ['GET'])]
    public function statistics(ReclamationRepository $reclamationRepo, SuiviReclamationRepository $suiviRepo): Response
    {
        $count = $reclamationRepo->countAll();
        $oldest = $reclamationRepo->findOldest();
        $newest = $reclamationRepo->findNewest();
        $suivi = $suiviRepo->countAll();
        $dailyCounts = $reclamationRepo->countByDay();
        return $this->render('reclamation/stats.html.twig', [
            'count' => $count,
            'oldest' => $oldest,
            'newest' => $newest,
            'suivi' => $suivi,
            'dailyCounts' => $dailyCounts,
        ]);
    }

    
    #[Route('/front', name: 'app_reclamation_index_front', methods: ['GET'])]
    public function indexF(EntityManagerInterface $entityManager): Response
    {
        $reclamations = $entityManager
            ->getRepository(Reclamation::class)
            ->findAll();

        return $this->render('reclamation/indexFront.html.twig', [
            'reclamations' => $reclamations,
        ]);
    }
  
  /*  #[Route('/update/image', name: 'upload_image', methods: ['GET', 'POST'])]
    public function updateImage(Request $request,FlashBagInterface $flashBagInterface)
    {
        $image = $request->files->get("image");
        $image_name=$image->getClientOriginalName();
        $image->move($this->getParameter("image_directory"),$image_name);
        
        $reclamation=new reclamation();
        $reclamation->setImage($image_name);
        $entityManager =$this->getDoctrine()->getManager();
        $entityManager->persist($reclamation);
        $entityManager->flush();
        $flashMessage->add("success");
        return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
    }
*/
#[Route('/export-reclamations', name: 'export_reclamations')]
public function exportReclamations(ReclamationRepository $reclamationRepository): Response
{
    // Get the data from the repository
    $reclamations = $reclamationRepository->findAll();
    
    // Create a new Spreadsheet object
    $spreadsheet = new Spreadsheet();
    
    // Set the title of the worksheet
    $spreadsheet->getActiveSheet()->setTitle('Reclamations');
    
    // Set the header row
    $spreadsheet->getActiveSheet()
        ->setCellValue('A1', 'ID')
        ->setCellValue('B1', 'Nom')
        ->setCellValue('C1', 'Prenom')
        ->setCellValue('D1', 'Adresse')
        ->setCellValue('E1', 'Contenu')
        ->setCellValue('F1', 'Date de création');
       
    
    // Add the data rows
    $row = 2;
    foreach ($reclamations as $reclamation) {
        $spreadsheet->getActiveSheet()
            ->setCellValue('A' . $row, $reclamation->getId())
            ->setCellValue('B' . $row, $reclamation->getNom())
            ->setCellValue('C' . $row, $reclamation->getPrenom())
            ->setCellValue('D' . $row, $reclamation->getAdresse())
            ->setCellValue('E' . $row, $reclamation->getContenu())
            ->setCellValue('F' . $row, $reclamation->getDatecreation()->format('Y-m-d'));
            
        $row++;
    }
    
    // Create a new Xlsx writer and write the data to a file
    $writer = new Xlsx($spreadsheet);
    $filePath = 'reclamations.xlsx';
    $writer->save($filePath);
    
    // Return the file as a response
    $response = new BinaryFileResponse($filePath);
    $response->setContentDisposition(ResponseHeaderBag::DISPOSITION_ATTACHMENT, 'reclamations.xlsx');
    return $response;
}
   




    #[Route('/new', name: 'app_reclamation_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation);
        $form->handleRequest($request);
        $reclamation->setDatecreation(new \DateTime());

        if ($form->isSubmitted()) {
            $image = $request->files->get("image");
            if ($image) {
                $image_name = $image->getClientOriginalName();
                $image->move($this->getParameter("image_directory"), $image_name);
                $reclamation->setImage($image_name);
         
            }


            $entityManager->persist($reclamation);
            $entityManager->flush();

            return $this->redirectToRoute('app_reclamation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('reclamation/newback.html.twig', [
            'reclamation' => $reclamation,
            'form' => $form,
        ]);
    }


   
    #[Route('/{id}/newfront', name: 'app_reclamation_newfront', methods: ['GET', 'POST'])]
    public function newfront(Request $request, EntityManagerInterface $entityManager): Response
    {
        $reclamation = new Reclamation();
        $form = $this->createForm(ReclamationType::class, $reclamation,);
        $form->handleRequest($request);
        $reclamation->setDatecreation(new \DateTime());
    
        if ($form->isSubmitted()) {
            // check if a similar content exists
            $existingReclamation = $entityManager
                ->getRepository(Reclamation::class)
                ->findOneBy([
                    'contenu' => $reclamation->getContenu(),
                    'nom' => $reclamation->getNom(),
                    'prenom' => $reclamation->getPrenom(),
                    'adresse' => $reclamation->getAdresse(),
                ]);
    
            if ($existingReclamation) {
                // if the same reclamation exists, add a warning message
                $this->addFlash('warning', 'This reclamation has already been submitted.');
            } else {
                // if the same reclamation does not exist, persist and flush the new reclamation
                // check if the reclamation text contains bad words
            
                $id = $request->attributes->get('id');
                $cleanedContenu = \ConsoleTVs\Profanity\Builder::blocker($reclamation->getContenu())->filter();
                $reclamation->setContenu($cleanedContenu);

templates/reclamation/_delete_form.html.twig
<form method="post" action="{{ path('app_reclamation_delete', {'id': reclamation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reclamation.id) }}">
    <button class="btn btn-block btn-danger">delete</button>
</form>

templates/reclamation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/reclamation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier Reclamation{% endblock %}
{% block slider %}{% endblock %}
{% block data %}
    {#<div class="row">


     <string>   <div  style="display: flex;align-items: center;justify-content: center;margin-top:-90px; padding:50px; font-weight: 900;position:relative ; left:300px;  "> </string>

          <div class="card">
 <div class="card-body">
 <div class="card-body">
              <h5 class=""  style= "color:blue ;display: flex; align-items: center; justify-content: center; padding-bottom:30px; font-weight: 900">Edit Reclamation</h5>
   

    {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>

    {{ include('reclamation/_delete_form.html.twig') }}
      </div>
        </div>
</div>
    </div>#}
    <div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Modifier Reclamation</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
        
        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 main-col offset-md-3">
                	<div class="mb-4">
                    {{ form_start(form) }}
                       <form method="POST" action="#" id="CustomerLoginForm" accept-charset="UTF-8" class="contact-form">	
                          {{ include('reclamation/_form.html.twig', {'button_label': 'Update'}) }}
                     </form>
                      {{ form_end(form) }}
                    </div>
               	</div>
            </div>
        </div>
       
    </div>
{% endblock %}
{% block newsletter %}{% endblock %}

templates/reclamation/index.html.twig
{% extends 'back.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css">
    <style>
        /* your custom styles here */
    </style>
{% endblock %}

{% block body %}
    <h1 class="h3 mb-3">Liste des reclamations</h1>
    <div class="form-group">
        <label for="search">Search:</label>
        <input class="form-control form-control-navbar" id="searchInput" type="search" placeholder="Search" aria-label="Search">
    </div>

    <div class="table-responsive">
        <table class="table table-striped table-hover" id="reclamation-table">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Prenom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Contenu</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody id="prev">
                {% for reclamation in reclamations %}
                    <tr>
                        <td>{{ reclamation.nom }}</td>
                        <td>{{ reclamation.prenom }}</td>
                        <td>{{ reclamation.adresse }}</td>
                        <td>{{ reclamation.contenu }}</td>
                        <td>{{ reclamation.datecreation ? reclamation.datecreation|date('Y-m-d') : '' }}</td>
                        <td>
                            <a href="{{ path('app_reclamation_show_back', {'id': reclamation.id}) }}" class=""><img src="{{ asset('front/assets/images/detail.png') }}" height="30" width="30"></a>
                            <a href="{{ path('app_suivi_reclamation_new_answer', {'id': reclamation.id}) }}" class="">Answer</a>
                        </td>
                    </tr>
                {% else %}
                    <tr>

                        <td colspan="6" class="text-center">No records found
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            <tbody id="new"> </tbody>
        </table>
        <a href="{{ path('export_reclamations')}}" class="">Excel</a>
    </div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
    function searchTable() {
        var queryy = document.getElementById("searchInput").value;
        
        if (queryy.length === 0) {
            $('#prev').show()
            $('#new').hide()
            $('#new').empty()

        }
        else {
                  $.ajax({
            url: "/test",
            type: "POST",
            data: {query: queryy},
            success: function(retour){
                if(retour){
                    $('#prev').hide()
                    $('#new').empty()
                     $('#new').show()

                    $.each(JSON.parse(retour), function(i, obj) {
                        var row = "<tr>" +
                            "<td>" + obj.nom + "</td>" +
                            "<td>" + obj.prenom + "</td>" +
                            "<td>" + obj.adresse + "</td>" +
                            "<td>" + obj.contenu + "</td>" +
                            "<td>" + obj.datecreation + "</td>" +
                            "</tr>";
                        $('#new').append(row);
                    });
                }
                else
                {
                     $('#prev').show()
                     $('#new').hide()
                     $('#new').empty()
                }
            }
        });



        }
      
    }

    $(document).ready(function() {
        $("#searchInput").on("keyup", searchTable);
    });
</script>
{% endblock %}

templates/reclamation/indexFront.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reclamation{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('path/to/style.css') }}">
{% endblock %}

{% block contentR %}
    <div id="page-content">
        <!--Page Title-->
        <div class="page section-header text-center">
            <div class="page-title">
                <div class="wrapper"><h1 class="page-width">Liste des reclamations</h1></div>
            </div>
        </div>
        <!--End Page Title-->

        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nom</th>
                    <th scope="col">Prenom</th>
                    <th scope="col">Adresse</th>
                    <th scope="col">Contenu</th>
                    <th scope="col">Date de création</th>
                    <th scope="col">Etat</th>
                    <th scope="col">Actions</th>
                </tr>
            </thead>
            <tbody>
            {% for reclamation in reclamations %}
                <tr>
                    <td>{{ reclamation.nom }}</td>
                    <td>{{ reclamation.prenom }}</td>
                    <td>{{ reclamation.adresse }}</td>
                    <td>{{ reclamation.contenu }}</td>
                    <td>{{ reclamation.datecreation|date('Y-m-d H:i:s') }}</td>
                    <td> {% if reclamation.etat == 0 %}
                <span class="badge badge-danger">Non ouverte</span>
              {% elseif reclamation.etat == 1 %}
                <span class="badge badge-ok">ouverte</span>
              {% else %}
                <span class="badge badge-success">Traité</span>
              {% endif %}</td>
                    <td>
                        <a href="{{ path('app_reclamation_show', {'id': reclamation.id}) }}">show</a>
                        <a href="{{ path('app_reclamation_edit', {'id': reclamation.id}) }}">edit</a>
                          
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="6">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
          <div class="text-center">
            
            <!-- ... -->

<li class="nav-item">

</li>

<!-- ... -->

        </div>
    </div>
{% endblock %}

templates/reclamation/indextri.html.twig
{% extends 'back.html.twig' %}

{% block title %}Consulter Reclamations{% endblock %}

{% block body %}
<h1 class="h3 mb-3">Consulter Reclamations</h1>

{% if reclamations|length %}
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Adresse</th>
                <th>Contenu</th>
                <th>Date de création</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.nom }}</td>
                <td>{{ reclamation.prenom }}</td>
                <td>{{ reclamation.adresse }}</td>
                <td>{{ reclamation.contenu }}</td>
                <td>{{ reclamation.datecreation ? reclamation.datecreation|date('Y-m-d') : '' }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p>No reclamations found.</p>
{% endif %}

{% endblock %}

templates/reclamation/indextri2.html.twig
{% extends 'back.html.twig' %}

{% block title %}Consulter Reclamations{% endblock %}

{% block body %}
<h1 class="h3 mb-3">Consulter Reclamations</h1>

{% if reclamations|length %}
<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Adresse</th>
                <th>Contenu</th>
                <th>Date de création</th>
            </tr>
        </thead>
        <tbody>
        {% for reclamation in reclamations %}
            <tr>
                <td>{{ reclamation.nom }}</td>
                <td>{{ reclamation.prenom }}</td>
                <td>{{ reclamation.adresse }}</td>
                <td>{{ reclamation.contenu }}</td>
                <td>{{ reclamation.datecreation ? reclamation.datecreation|date('Y-m-d') : '' }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% else %}
<p>No reclamations found.</p>
{% endif %}

{% endblock %}

templates/reclamation/new.html.twig
{% extends 'base.html.twig' %}
{#
{% block title %}{% endblock %}

{% block body %}
<div class="row">


     <string>   <div  style="display: flex;align-items: center;justify-content: center;margin-top:-90px; padding:50px; font-weight: 900;position:relative ; left:300px;  "> </string>

          <div class="card">
 <div class="card-body">
              <h5 class=""  style= "color:blue ;display: flex; align-items: center; justify-content: center; padding-bottom:30px; font-weight: 900">Add Reclamation</h5>
   
    {{ include('reclamation/_form.html.twig') }}

    <a href="{{ path('app_reclamation_index') }}">back to list</a>
    </div>
        </div>
</div>
    </div>

{% endblock %}#}
{% block title %}Ajouter Reclamation{% endblock %}
{% block slider %}{% endblock %}
{% block newR %}
<div id="page-content">
    	<!--Page Title-->
    	<div class="page section-header text-center">
			<div class="page-title">
        		<div class="wrapper"><h1 class="page-width">Ajouter Une Reclamation</h1></div>
      		</div>
		</div>
        <!--End Page Title-->
        
        <div class="container">
        	<div class="row">
                <div class="col-12 col-sm-12 col-md-6 col-lg-6 main-col offset-md-3">
                	<div class="mb-4">
                    {{ form_start(form) }}
                       <form method="POST" action="#"  class="contact-form">	
                          <div class="row">
	                          <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    {{ form_label(form.nom) }}
                                    {{ form_widget(form.nom, {'attr': {'class': 'form-control'}}) }}
                                    {{ form_errors(form.nom) }}
                                </div>
                               </div>
                               <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    {{ form_label(form.prenom) }}
                                    {{ form_widget(form.prenom, {'attr': {'class': 'form-control'}}) }}
                                    {{ form_errors(form.prenom) }}
                                </div>
                               </div>
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    {{ form_label(form.adresse) }}
                                    {{ form_widget(form.adresse, {'attr': {'class': 'form-control'}}) }}
                                    {{ form_errors(form.adresse) }}
                                </div>
                            </div>
                            <div class="col-12 col-sm-12 col-md-12 col-lg-12">
                                <div class="form-group">
                                    {{ form_label(form.contenu) }}
                                    {{ form_widget(form.contenu, {'attr': {'class': 'form-control'}}) }} 
                                    {{ form_errors(form.contenu) }}                       	
                                </div>
                            </div>
                          </div>
                          <div class="row">
                            <div class="text-center col-12 col-sm-12 col-md-12 col-lg-12">
                                <button class="btn" type="submit">{{ button_label|default('Save') }}</button>
                            </div>
                         </div>
                     </form>
                      {{ form_end(form) }}
                    </div>
               	</div>
            </div>
        </div>
       
    </div>
{% endblock %}
{% block newsletter %}{% endblock %}